/**
 * @file src/installer/hookInstaller.ts
 * @description Git hook installer and Lefthook orchestrator.
 *
 * Installs mechanical git hooks in .git/hooks/ (pre-commit, pre-push) that invoke
 * Lefthook and route execution through the agent diagnostic streamer.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';
import type { HookInstallResult } from '../types/index.js';

/**
 * Options for configuring HookInstaller
 */
export interface HookInstallerOptions {
  /** Target repository root directory (defaults to process.cwd()) */
  cwd?: string;
}

/**
 * Mechanical Git Hook Installer.
 * Ensures .git/hooks/pre-commit and .git/hooks/pre-push are present and executable.
 */
export class HookInstaller {
  /** Resolved absolute path of the target repository */
  private readonly rootPath: string;

  /**
   * Initialize a new HookInstaller instance
   * @param options Target path string or HookInstallerOptions object
   */
  constructor(options: string | HookInstallerOptions = {}) {
    if (typeof options === 'string') {
      this.rootPath = path.resolve(options);
    } else {
      this.rootPath = path.resolve(options.cwd || process.cwd());
    }
  }

  /**
   * Install mechanical git hooks into the repository.
   * First attempts native `npx lefthook install`, and falls back to writing
   * robust POSIX shell hook wrappers directly to `.git/hooks/`.
   *
   * @returns HookInstallResult with details of installed hooks
   */
  public install(): HookInstallResult {
    const gitDir = path.join(this.rootPath, '.git');
    const gitHooksDir = path.join(gitDir, 'hooks');
    let lefthookInstalled = false;
    const installedHooks: string[] = [];

    // Check if .git directory exists
    if (!fs.existsSync(gitDir)) {
      return {
        lefthookInstalled: false,
        gitHooksPath: gitHooksDir,
        installedHooks: [],
        message: 'No .git repository found. Git hooks skipped (not a git repository).',
      };
    }

    // Ensure .git/hooks directory exists
    if (!fs.existsSync(gitHooksDir)) {
      fs.mkdirSync(gitHooksDir, { recursive: true });
    }

    // 1. Attempt to run `npx lefthook install` natively
    try {
      execFileSync('npx', ['lefthook', 'install', '-f'], {
        cwd: this.rootPath,
        stdio: 'pipe',
        timeout: 10000,
      });
      lefthookInstalled = true;
    } catch {
      // Fall back to direct hook file creation if lefthook CLI is not present
      lefthookInstalled = false;
    }

    // 2. Ensure pre-commit hook script exists and is executable
    const preCommitPath = path.join(gitHooksDir, 'pre-commit');
    const preCommitScript = `#!/bin/sh
# Generated by @heretek-ai/agent-proof - Mechanical Pre-Commit Hard Gate
set -e

if command -v npx >/dev/null 2>&1; then
  npx lefthook run pre-commit
elif command -v lefthook >/dev/null 2>&1; then
  lefthook run pre-commit
else
  echo "[agent-proof] Warning: neither npx nor lefthook found. Skipping pre-commit gate."
fi
`;
    fs.writeFileSync(preCommitPath, preCommitScript, { mode: 0o755 });
    installedHooks.push('pre-commit');

    // 3. Ensure pre-push hook script exists and is executable
    const prePushPath = path.join(gitHooksDir, 'pre-push');
    const prePushScript = `#!/bin/sh
# Generated by @heretek-ai/agent-proof - Mechanical Pre-Push Hard Gate
set -e

if command -v npx >/dev/null 2>&1; then
  npx lefthook run pre-push
elif command -v lefthook >/dev/null 2>&1; then
  lefthook run pre-push
fi
`;
    fs.writeFileSync(prePushPath, prePushScript, { mode: 0o755 });
    installedHooks.push('pre-push');

    return {
      lefthookInstalled,
      gitHooksPath: gitHooksDir,
      installedHooks,
      message: lefthookInstalled
        ? 'Lefthook hooks successfully installed and verified.'
        : 'Installed direct POSIX git hook wrappers for Lefthook in .git/hooks/.',
    };
  }
}

/**
 * Functional convenience wrapper to install git hooks
 * @param cwd Target repository directory or options
 */
export function installHooks(cwd?: string | HookInstallerOptions): HookInstallResult {
  return new HookInstaller(cwd).install();
}
