import type { StackDetectionResult } from '../../types/index.js';

export function generateLefthookConfig(detection: StackDetectionResult): string {
  const preCommitCommands: string[] = [];
  const prePushCommands: string[] = [];

  // Stage 2: Pre-Commit Hard Gates (< 2.0s execution target)
  if (detection.jsTs.detected) {
    preCommitCommands.push(`    biome-check:
      glob: "*.{js,ts,jsx,tsx,json,jsonc}"
      run: npx @biomejs/biome check --staged --no-errors-on-unmatched`);
  }

  if (detection.python.detected) {
    preCommitCommands.push(`    ruff-check:
      glob: "*.py"
      run: ruff check --staged --fix`);
  }

  if (detection.go.detected) {
    preCommitCommands.push(`    gosec-check:
      glob: "*.go"
      run: gosec -quiet ./...`);
  }

  if (detection.rust.detected) {
    preCommitCommands.push(`    cargo-deny:
      glob: "Cargo.{toml,lock}"
      run: cargo deny check`);
  }

  // Universal deterministic AI slop detection
  preCommitCommands.push(`    aislop-scan:
      run: npx aislop scan --staged --fail-on 50`);

  // Universal secret scanning
  preCommitCommands.push(`    secret-scan:
      run: trufflehog git file://. --staged --only-verified`);

  // Universal typo & spelling check
  preCommitCommands.push(`    typo-check:
      run: typos --staged`);

  // Workflow validation
  if (detection.infra.hasWorkflows) {
    preCommitCommands.push(`    actionlint:
      glob: ".github/workflows/*.{yml,yaml}"
      run: actionlint`);
  }

  // Stage 3: Pre-Push / CI Graph Audit
  if (detection.jsTs.detected) {
    prePushCommands.push(`    fallow-audit:
      run: npx fallow audit`);
  }

  if (detection.jsTs.isMonorepo) {
    prePushCommands.push(`    monorepo-sherif:
      run: npx setup-sherif`);
  }

  // Universal API attack surface mapping
  prePushCommands.push(`    noir-scan:
      run: noir scan . --ai-context -f sarif`);

  if (detection.rust.detected && !prePushCommands.some(c => c.includes('cargo-deny'))) {
    prePushCommands.push(`    cargo-deny:
      run: cargo deny check`);
  }

  const parts = [
    '# Generated by @heretek-ai/agent-proof - Mechanical Hard Gate Orchestration',
    '# Stage 2: Synchronous Local Pre-Commit Hard Gate (< 2.0s budget)',
    'pre-commit:',
    '  parallel: true',
    '  commands:',
    preCommitCommands.join('\n'),
    '',
    '# Stage 3: Full CI & Codebase Graph Governance',
    'pre-push:',
    '  commands:',
    prePushCommands.join('\n'),
    '',
  ];

  return parts.join('\n');
}
